# Generated by Django 3.1.1 on 2020-09-17 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='a1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='a2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='a3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='a4',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='a5',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
